### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Taccio33** [Gameonlp/OreDepos#2]
Version: 1.16.6; Forge: 36.2.29.
[crash-2022-04-30_21.59.16-server.txt](https://github.com/Gameonlp/OreDepos/files/8597723/crash-2022-04-30_21.59.16-server.txt)

**Comment by Gameonlp** [comment]
Could it be that one of the mods you are using enables you to mine any of the vanilla ores barehand?

**Comment by Taccio33** [comment]
Not that I know. But in a single player testing world using only a few mods it doesn't crash. I could not pinpoint a specific mod tho, I'm sorry.

**Comment by Gameonlp** [comment]
The crash you posted is a real crash, so i am grateful. I will publish version 1.0.7 today with new content and 2 (probable) bug fixes, try to reproduce the crash then if i can ask you to do.

**Comment by Taccio33** [comment]
The crash stopped, so thanks for that. On the other hand vanilla ore deposit don't get recognized by the miner (diomd, gold, coal) whereas modded ore deposit do (nickel, aluminum). Anyway I'm going to close this issue!
