### ISSUE TITLE
Create drills always break deposit blocks

### ISSUE THREAD

**Issue by Derpford** [Gameonlp/OreDepos#8]
When a deposit block is broken by a Create drill, it drops exactly one ore chunk and then disappears.  This happens whether the drill is stationary or part of a Contraption.

I'm not sure how much you can really do to resolve this, but ideally Create drills would behave exactly like pickaxes do--that is, breaking the block with a Create drill drops one ore chunk but doesn't remove the block.

**Comment by Gameonlp** [comment]
Sadly there is no general API for block breaking, so create just does its best by dropping what the block would drop and then forcefully replacing it.

**Comment by Derpford** [comment]
I wonder if the Create devs could add some way of telling the drill that it shouldn't actually replace the block.

**Comment by Derpford** [comment]
According to this: https://github.com/Creators-of-Create/Create/issues/3061

There's a tag that Create's drills look for now, called NO_BREAK_DROPS.

**Comment by Gameonlp** [comment]
Interesting, will look into this later after work

**Comment by Derpford** [comment]
https://github.com/dadobug1111/DadobugBedrockOres/issues/6#issuecomment-1180885715

This issue on Bedrock Ores also seems relevant.

**Comment by Gameonlp** [comment]
> According to this: [Creators-of-Create/Create#3061](https://github.com/Creators-of-Create/Create/issues/3061)
> 
> There's a tag that Create's drills look for now, called NO_BREAK_DROPS.

Sadly the tag never got implemented

> [dadobug1111/DadobugBedrockOres#6 (comment)]
> 
> This issue on Bedrock Ores also seems relevant.

The solution they outline leads to even worse results. Block breakers which behave like miners work fine, block breakers like cyclics block breaker create infinite drops at sonic speed.
